variables:
    # hub.docker.com/tlong1904/shoeshop:vvv
    DOCKER_IMAGE: ${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
    DOCKER_CONTAINER: ${CI_PROJECT_NAME}

stages:
    - build&push
    - deploy
    - showlog
build&push:
    stage: build&push
    variables:
        GIT_STRATEGY: clone
    before_script:
        - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    script:
        - docker build -t $DOCKER_IMAGE .
        - docker push $DOCKER_IMAGE
    tags:
        - dev-server
    only:
        - tags
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    before_script:
        - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    script:
        - docker pull $DOCKER_IMAGE
        - docker rm -f $DOCKER_CONTAINER
        - docker run --name $DOCKER_CONTAINER -dp 8888:8080 $DOCKER_IMAGE
    tags:
        - dev-server
    only:
        - tags
showlog:
    stage: showlog
    variables:
        GIT_STRATEGY: none
    script:
        - sleep 20
        - docker logs $DOCKER_CONTAINER
    tags:
        - dev-server
    only:
        - tags
